version: '3.1'

services:
# Если хотите подключить базу данных
#  db:
# ВНИМАТЕЛЬНО! ВОТ ЭТО НАЗВАНИЕ СЕРВИСА - db - ДОЛЖНО БЫТЬ УКАЗАНО В БОТЕ КАК host В ПОДКЛЮЧЕНИИ К БАЗЕ ИЗ БОТА
# ТО ЕСТЬ НЕ АЙПИШНИК И НЕ ЛОКАЛХОСТ, А db
#    container_name: database
#    image: sameersbn/postgresql:10-2
#     env_file:
#       - ".env"
#    environment:
#      PG_PASSWORD: $PGPASSWORD
#    restart: always
#    ports:
#      - 5432:5432
#    networks:
#      - botnet
#    volumes:
#      - ./postgres:/var/lib/postgresql
#
  tgbot:
    container_name: ans_bot
    build:
      context: .
    command: python3 just_go.py
    networks:
      - bot_net
    restart: always
    env_file:
      - ".env"
    volumes:
      - .:/src
    # Бот стартует после запуска базы
#    depends_on:
#      - db

# указываются используемые сети
networks:
  bot_net:
    # указывается драйвер сети
    driver: bridge
